import Column from '@/shared/entities/Column'
import Task from '@/shared/entities/Task'

export const mockColumns: Column[] = [
  new Column({ id: '1', title: 'To Do', order: 1 }),
  new Column({ id: '2', title: 'In Progress', order: 2 }),
  new Column({ id: '3', title: 'Done', order: 3 }),
  new Column({ id: '4', title: 'Backlog', order: 4 }),
  new Column({ id: '5', title: 'Blocked', order: 5 }),
  new Column({ id: '6', title: 'Review', order: 6 }),
]

export const mockTasks: Task[] = [
  new Task({ id: '1', title: 'Task 1', order: 1, columnId: '1' }),
  new Task({ id: '2', title: 'Task 2', order: 2, columnId: '1' }),
  new Task({ id: '3', title: 'Task 3', order: 3, columnId: '1' }),
  new Task({ id: '4', title: 'Task 4', order: 4, columnId: '1' }),
  new Task({ id: '5', title: 'Task 5', order: 5, columnId: '1' }),
  new Task({ id: '6', title: 'Task 6', order: 6, columnId: '1' }),
  new Task({ id: '7', title: 'Task 7', order: 7, columnId: '1' }),
  new Task({ id: '8', title: 'Task 8', order: 8, columnId: '1' }),
  new Task({ id: '9', title: 'Task 9', order: 9, columnId: '1' }),
  new Task({ id: '10', title: 'Task 10', order: 10, columnId: '1' }),
  new Task({ id: '11', title: 'Task 11', order: 11, columnId: '1' }),
  new Task({ id: '12', title: 'Task 12', order: 12, columnId: '1' }),
  new Task({ id: '13', title: 'Task 13', order: 13, columnId: '1' }),
  new Task({ id: '14', title: 'Task 14', order: 14, columnId: '1' }),
  new Task({ id: '15', title: 'Task 15', order: 15, columnId: '1' }),
  new Task({ id: '16', title: 'Task 16', order: 16, columnId: '1' }),
  new Task({ id: '17', title: 'Task 17', order: 17, columnId: '1' }),
  new Task({ id: '18', title: 'Task 18', order: 18, columnId: '1' }),
  new Task({ id: '19', title: 'Task 19', order: 19, columnId: '1' }),
  new Task({ id: '20', title: 'Task 20', order: 20, columnId: '1' }),
  new Task({ id: '21', title: 'Task 21', order: 21, columnId: '1' }),
  new Task({ id: '22', title: 'Task 22', order: 1, columnId: '2' }),
  new Task({ id: '23', title: 'Task 23', order: 2, columnId: '2' }),
  new Task({ id: '24', title: 'Task 24', order: 3, columnId: '2' }),
  new Task({ id: '25', title: 'Task 25', order: 4, columnId: '2' }),
  new Task({ id: '26', title: 'Task 26', order: 5, columnId: '2' }),
  new Task({ id: '27', title: 'Task 27', order: 1, columnId: '3' }),
  new Task({ id: '28', title: 'Task 28', order: 2, columnId: '3' }),
  new Task({ id: '29', title: 'Task 29', order: 3, columnId: '3' }),
  new Task({ id: '30', title: 'Task 30', order: 4, columnId: '3' }),
  new Task({ id: '31', title: 'Task 31', order: 5, columnId: '3' }),
  new Task({ id: '32', title: 'Task 32', order: 1, columnId: '4' }),
  new Task({ id: '33', title: 'Task 33', order: 2, columnId: '4' }),
  new Task({ id: '34', title: 'Task 34', order: 1, columnId: '5' }),
  new Task({ id: '35', title: 'Task 35', order: 2, columnId: '5' }),
  new Task({ id: '36', title: 'Task 36', order: 1, columnId: '6' }),
  new Task({ id: '37', title: 'Task 37', order: 2, columnId: '6' }),
]
