import { v4 as uuidv4 } from 'uuid'
import Column from '@/shared/entities/Column'
import Task from '@/shared/entities/Task'

export const mockColumns: Column[] = [
  new Column({ id: uuidv4(), title: 'To Do', order: 1 }),
  new Column({ id: uuidv4(), title: 'In Progress', order: 2 }),
  new Column({ id: uuidv4(), title: 'Done', order: 3 }),
  new Column({ id: uuidv4(), title: 'Backlog', order: 4 }),
  new Column({ id: uuidv4(), title: 'Blocked', order: 5 }),
  new Column({ id: uuidv4(), title: 'Review', order: 6 }),
]

export const mockTasks: Task[] = [
  new Task({
    id: uuidv4(),
    title: 'Task 1',
    order: 1,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 2',
    order: 2,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 3',
    order: 3,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 4',
    order: 4,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 5',
    order: 5,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 6',
    order: 6,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 7',
    order: 7,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 8',
    order: 8,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 9',
    order: 9,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 10',
    order: 10,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 11',
    order: 11,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 12',
    order: 12,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 13',
    order: 13,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 14',
    order: 14,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 15',
    order: 15,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 16',
    order: 16,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 17',
    order: 17,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 18',
    order: 18,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 19',
    order: 19,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 20',
    order: 20,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 21',
    order: 21,
    columnId: mockColumns[0].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 22',
    order: 1,
    columnId: mockColumns[1].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 23',
    order: 2,
    columnId: mockColumns[1].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 24',
    order: 3,
    columnId: mockColumns[1].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 25',
    order: 4,
    columnId: mockColumns[1].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 26',
    order: 5,
    columnId: mockColumns[1].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 27',
    order: 1,
    columnId: mockColumns[2].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 28',
    order: 2,
    columnId: mockColumns[2].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 29',
    order: 3,
    columnId: mockColumns[2].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 30',
    order: 4,
    columnId: mockColumns[2].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 31',
    order: 5,
    columnId: mockColumns[2].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 32',
    order: 1,
    columnId: mockColumns[3].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 33',
    order: 2,
    columnId: mockColumns[3].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 34',
    order: 1,
    columnId: mockColumns[4].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 35',
    order: 2,
    columnId: mockColumns[4].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 36',
    order: 1,
    columnId: mockColumns[5].id,
  }),
  new Task({
    id: uuidv4(),
    title: 'Task 37',
    order: 2,
    columnId: mockColumns[5].id,
  }),
]
