import GetAuthUserService from '@/frontend/features/Auth/GetAuthUserService'
import { NextAuthProvider } from '@/frontend/features/Auth/NextAuthProvider'
import AppContainer from '@/frontend/features/Layout/AppContainer'
import '@/frontend/styles/globals.css'
import { cn } from '@/shared/utilities/classNameMerge'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
// import apolloClient from '@/frontend/infra/Apollo/ApolloClient'
// import { ApolloProvider } from '@apollo/client'
import { ApolloWrapper } from '@/frontend/infra/Apollo/ApolloWrapper'

const inter = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const response = await new GetAuthUserService().execute()
  const authUser = response.data?.user

  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable
        )}
      >
        <NextAuthProvider authUser={authUser}>
          <ApolloWrapper>
            {/* <ApolloProvider client={apolloClient}> */}
            <AppContainer>{children}</AppContainer>
            {/* </ApolloProvider> */}
          </ApolloWrapper>
        </NextAuthProvider>
      </body>
    </html>
  )
}
