import type { Metadata } from 'next'
import '../frontend/styles/globals.css'
import { Inter as FontSans } from 'next/font/google'
import { cn } from '@/design-system/lib/utils'
import { ThemeProvider } from '@/design-system/theme/theme-provider'
import { ApolloProvider } from '@apollo/client'
import apolloClient from '@/frontend/infra/Apollo/ApolloClient'

const inter = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable
        )}
      >
        {/* <ApolloProvider client={apolloClient}> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        {/* </ApolloProvider> */}
      </body>
    </html>
  )
}
